os:
  - linux
#  - osx
dist: xenial
language: python
sudo: false
env:
  - TEST_MODE=run_tests
python:
  - "2.7"
  - "3.6"
  - "3.7"
  - "3.8-dev"  # 3.8 development branch
  - "nightly"  # nightly build
install: .travis/install.sh
script: .travis/test.sh
after_success: .travis/finish.sh
matrix:
  include:
    - os: linux
      python: "2.7"
      env: TEST_MODE=check_style
    - os: linux
      python: "2.7"
      env: TEST_MODE=coverage
    - os: linux
      python: "3.7"
      env: TEST_MODE=check_style
    - os: linux
      python: "3.7"
      env: TEST_MODE=coverage
